cases:
  donat:
    title-above-case: '&#c88123К&#cd7c24е&#d27825й&#d77326с &#dc6e27с &#e16a28д&#e66529о&#eb612aн&#f05c2bа&#f5572cт&#fa532dо&#ff4e2eм'
    title-above-case-y-offset: 1.0
    luck_work: true
    circle-animation:
      random-rewards: false
      reward-radius: 1.5
      chest-open-sound: BLOCK_CHEST_OPEN
      chest-close-sound: BLOCK_CHEST_CLOSE
      start:
        delay: 20
        spawn-interval: 20
      open:
        reward-up-ticks: 40
        rotate-into-place-angle: 12.0
      spin:
        start-angle-per-tick: 12.0
        minimal-angle-per-tick: 2.0
        minimum-slowdown-ticks: 140
        maximum-slowdown-ticks: 140
        minimum-idle-ticks: 0
        maximum-idle-ticks: 0
      end:
        delay: 60
        down-ticks: 10
        rotate-into-place-angle: 10.0
    spinning-animation:
      lift-height: 2.0
      lift-duration: 40
      spin-duration: 80
      change-interval: 20
      drop-duration: 40
      lift-sound: BLOCK_ANVIL_LAND
      drop-sound: ENTITY_PLAYER_LEVELUP
    animation:
      type: circle
    messages:
      case-already-opening:
        - Кто-то уже открывает кейс
      not-have-keys-for-case:
        - У вас нет ключа от этого кейса
    locations: []
    prize-messages:
      - '----------'
      - ' %player_name% выиграл %prize_name%'
      - '%luck% &7Покупка кейсов здесь: &bXromoWorld.ru'
      - '----------'
    open:
      type: key
    rewards:
      rogue:
        material: CYAN_SHULKER_BOX
        name: '&#7fc8b7R&#91d3c9o&#a2dfdbg&#b4eaedu&#c5f5ffe'
        glow: true
        chances:
          no_luck: 29.0
          luck15: 35.0
          luck30: 40.0
        send-title: false
        add-to-history: false
        prizes:
          first-prize:
            name: '&#7fc8b7R&#91d3c9o&#a2dfdbg&#b4eaedu&#c5f5ffe &7(1 мес.)'
            title:
              title: "Вам выпало: &#7fc8b7R&#91d3c9o&#a2dfdbg&#b4eaedu&#c5f5ffe &7(1 мес.)"
              subtitle: "Поздравляем!"
            commands:
              - lp user %player_name% parent set rogue
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          second-prize:
            name: '&#7fc8b7R&#91d3c9o&#a2dfdbg&#b4eaedu&#c5f5ffe &7(3 мес.)'
            commands:
              - lp user %player_name% parent set rogue
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          third-prize:
            name: '&#7fc8b7R&#91d3c9o&#a2dfdbg&#b4eaedu&#c5f5ffe &7(навсегда)'
            commands:
              - lp user %player_name% parent set rogue
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
      raider:
        material: PINK_SHULKER_BOX
        name: '&#ec3b30R&#eb324da&#ea286bi&#e81f88d&#e715a6e&#e60cc3r'
        glow: true
        chances:
          no_luck: 39.0
          luck15: 44.0
          luck30: 50.0
        send-title: false
        add-to-history: false
        prizes:
          first-prize:
            name: '&#ec3b30R&#eb324da&#ea286bi&#e81f88d&#e715a6e&#e60cc3r &7(1 мес.)'
            title:
              title: "Вам выпало: &#ec3b30R&#eb324da&#ea286bi&#e81f88d&#e715a6e&#e60cc3r &7(1 мес.)"
              subtitle: "Поздравляем!"
            commands:
              - lp user %player_name% parent set raider
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          second-prize:
            name: '&#ec3b30R&#eb324da&#ea286bi&#e81f88d&#e715a6e&#e60cc3r &7(3 мес.)'
            commands:
              - lp user %player_name% parent set raider
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          third-prize:
            name: '&#ec3b30R&#eb324da&#ea286bi&#e81f88d&#e715a6e&#e60cc3r &7(навсегда)'
            commands:
              - lp user %player_name% parent set raider
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
      warlord:
        material: LIGHT_BLUE_SHULKER_BOX
        name: '&#84e46cW&#72cd7fa&#5fb692r&#4d9fa5l&#3a87b7o&#2870car&#1559ddd'
        glow: true
        chances:
          no_luck: 25.0
          luck15: 30.0
          luck30: 35.0
        send-title: false
        add-to-history: true
        prizes:
          first-prize:
            name: '&#84e46cW&#72cd7fa&#5fb692r&#4d9fa5l&#3a87b7o&#2870car&#1559ddd &7(1 мес.)'
            title:
              title: "Вам выпало: &#84e46cW&#72cd7fa&#5fb692r&#4d9fa5l&#3a87b7o&#2870car&#1559ddd &7(1 мес.)"
              subtitle: "Поздравляем!"
            commands:
              - lp user %player_name% parent set warlord
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          second-prize:
            name: '&#84e46cW&#72cd7fa&#5fb692r&#4d9fa5l&#3a87b7o&#2870car&#1559ddd &7(3 мес.)'
            commands:
              - lp user %player_name% parent set warlord
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          third-prize:
            name: '&#84e46cW&#72cd7fa&#5fb692r&#4d9fa5l&#3a87b7o&#2870car&#1559ddd &7(навсегда)'
            commands:
              - lp user %player_name% parent set warlord
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
      overlord:
        material: PURPLE_SHULKER_BOX
        name: '&#8000ffO&#8600f5v&#8c00ebe&#9200e1r&#9800d7l&#9e00cdo&#a400c3r&#aa00b9d'
        glow: true
        chances:
          no_luck: 6.0
          luck15: 10.0
          luck30: 15.0
        send-title: true
        add-to-history: true
        prizes:
          first-prize:
            name: '&#8000ffO&#8600f5v&#8c00ebe&#9200e1r&#9800d7l&#9e00cdo&#a400c3r&#aa00b9d &7(1 мес.)'
            title:
              title: "Вам выпало: &#8000ffO&#8600f5v&#8c00ebe&#9200e1r&#9800d7l&#9e00cdo&#a400c3r&#aa00b9d &7(1 мес.)"
              subtitle: "Поздравляем!"
            commands:
              - lp user %player_name% parent set overlord
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          second-prize:
            name: '&#8000ffO&#8600f5v&#8c00ebe&#9200e1r&#9800d7l&#9e00cdo&#a400c3r&#aa00b9d &7(3 мес.)'
            commands:
              - lp user %player_name% parent set overlord
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          third-prize:
            name: '&#8000ffO&#8600f5v&#8c00ebe&#9200e1r&#9800d7l&#9e00cdo&#a400c3r&#aa00b9d &7(навсегда)'
            commands:
              - lp user %player_name% parent set overlord
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
      prime:
        material: LIME_SHULKER_BOX
        name: '&#3cff5bP&#41fa76r&#46f691i&#4af1abm&#4fecc6e'
        glow: true
        chances:
          no_luck: 1.0
          luck15: 3.0
          luck30: 5.0
        send-title: true
        add-to-history: true
        prizes:
          first-prize:
            name: '&#3cff5bP&#41fa76r&#46f691i&#4af1abm&#4fecc6e &7(1 мес.)'
            title:
              title: "Вам выпало: &#3cff5bP&#41fa76r&#46f691i&#4af1abm&#4fecc6e &7(1 мес.)"
              subtitle: "Поздравляем!"
            commands:
              - lp user %player_name% parent set prime
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          second-prize:
            name: '&#3cff5bP&#41fa76r&#46f691i&#4af1abm&#4fecc6e &7(3 мес.)'
            commands:
              - lp user %player_name% parent set prime
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
          third-prize:
            name: '&#3cff5bP&#41fa76r&#46f691i&#4af1abm&#4fecc6e &7(навсегда)'
            commands:
              - lp user %player_name% parent set prime
            chances:
              no_luck: 33.3
              luck15: 40
              luck30: 50
    particles:
      flame:
        particle: FLAME
        count: 15
        speed: 0.05
        xOffset: 0.5
        yOffset: 0.5
        zOffset: 0.5
      redstone:
        particle: REDSTONE
        count: 15
        speed: 0.2
        xOffset: 0.5
        yOffset: 0.5
        zOffset: 0.5
        r: 108
        g: 192
        b: 196
    menu:
      title: '&#c88123К&#cd7c24е&#d27825й&#d77326с &#dc6e27с &#e16a28д&#e66529о&#eb612aн&#f05c2bа&#f5572cт&#fa532dо&#ff4e2eм'
      size: 54
      cooldown:
        type: GLOBAL
        time: 20
      item-types:
        O:
          material: AIR
        X:
          material: ORANGE_STAINED_GLASS_PANE
          name: ' '
        P:
          material: PAPER
          name: '&#c88123К&#cd7c24е&#d27825й&#d77326с &#dc6e27с &#e16a28д&#e66529о&#eb612aн&#f05c2bа&#f5572cт&#fa532dо&#ff4e2eм
            &8(описание и цены)'
          lore:
            - '&fЦены на кейсы с донатом:'
            - '&e1 кейс &7- от &f99 р.&7 (99р/шт)'
        C:
          material: CHEST
          name: '&6&lОткрыть кейс'
          lore:
            - '&fКоличество кейсов:&#ff0000 %player_keys%'
            - '%lucks%'
            - '&fНажмите чтобы открыть кейс'
        W:
          material: ARROW
          name: '&6Последние выигрыши'
          lore:
            - '&6>'
            - '&6>'
            - '&6>'
      last-rewards:
        item-name: '%player_name% выйграл %prize_name%'
        item-lore:
          - '&6 '
          - 'Удача: %luck%'
          - 'Дата: %date%'
          - 'Сервер: %server_name%'
          - '&6 '
          - Проверь и ты свою удачу!
      inventory:
        - X X X X X X X X X
        - X O O O O O O O X
        - X O O O C O O O X
        - X O O O O O O P X
        - X X X X X X X X X
        - W O O O O O O O O
